spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rent_me
    username: doston
    password: doston123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs
